# Generated by Django 3.0.8 on 2020-10-31 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('esuits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esgroupmodel',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='作成日時'),
        ),
    ]
