# Generated by Django 3.0.8 on 2020-10-31 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esuits', '0003_auto_20201101_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='es_group_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='esuits.ESGroupModel', verbose_name='ES名'),
        ),
    ]
