# Generated by Django 3.0.8 on 2020-10-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esuits', '0005_auto_20201101_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='回答'),
        ),
    ]
