# Generated by Django 3.0.8 on 2020-11-05 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('esuits', '0008_auto_20201101_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='esgroupmodel',
            name='deadline_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='提出期限'),
        ),
    ]
