# Generated by Django 3.0.8 on 2020-11-06 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esuits', '0009_esgroupmodel_deadline_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCloudModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_url', models.URLField(verbose_name='企業ホームページ')),
                ('word_cloud_image_url', models.URLField(verbose_name='ワードクラウドURL')),
            ],
            options={
                'db_table': 'word_cloud',
            },
        ),
        migrations.AddField(
            model_name='esgroupmodel',
            name='word_cloud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esuits.WordCloudModel', verbose_name='ワードクラウド'),
        ),
    ]
