# Generated by Django 3.1.1 on 2020-11-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esuits', '0013_auto_20201107_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
