# Generated by Django 3.1.1 on 2020-11-29 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('esuits', '0014_auto_20201128_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyHomepageURLModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage_url', models.URLField(verbose_name='企業URL')),
                ('word_cloud_path', models.CharField(max_length=255, verbose_name='ワードクラウドパス')),
            ],
            options={
                'db_table': 'homepage_urls',
            },
        ),
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='企業名')),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='EntrySheetesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='選考種別')),
                ('is_editing', models.BooleanField(default=True, verbose_name='作成中or完成')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('deadline_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='提出期限')),
            ],
            options={
                'db_table': 'entry_sheets',
            },
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='質問')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='')),
                ('char_num', models.IntegerField(blank=True, default=0)),
                ('open_info', models.CharField(choices=[('public', '公開'), ('private', '非公開')], default='private', max_length=20, verbose_name='公開or非公開')),
                ('entry_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esuits.entrysheetesmodel', verbose_name='エントリーシート')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='es_group_id',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='tagmodel',
            name='author',
        ),
        migrations.AddField(
            model_name='tagmodel',
            name='author',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AlterModelTable(
            name='customusermodel',
            table='custom_users',
        ),
        migrations.AlterModelTable(
            name='tagmodel',
            table='tags',
        ),
        migrations.DeleteModel(
            name='ESGroupModel',
        ),
        migrations.DeleteModel(
            name='PostModel',
        ),
        migrations.DeleteModel(
            name='WordCloudModel',
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='esuits.TagModel', verbose_name='タグ名'),
        ),
        migrations.AddField(
            model_name='entrysheetesmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AddField(
            model_name='entrysheetesmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='esuits.companymodel', verbose_name='企業 '),
        ),
        migrations.AddField(
            model_name='entrysheetesmodel',
            name='homepage_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='esuits.companyhomepageurlmodel', verbose_name='ホームページURL'),
        ),
        migrations.AddField(
            model_name='companyhomepageurlmodel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esuits.companymodel', verbose_name='企業'),
        ),
    ]
