# Generated by Django 3.1.1 on 2020-11-29 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esuits', '0015_auto_20201129_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagmodel',
            old_name='author',
            new_name='authors',
        ),
    ]
