# Generated by Django 3.1.1 on 2020-11-29 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esuits', '0016_auto_20201129_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionmodel',
            old_name='open_info',
            new_name='is_open',
        ),
    ]
