# Generated by Django 3.1.1 on 2020-11-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esuits', '0017_auto_20201129_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='is_open',
            field=models.CharField(blank=True, choices=[('public', '公開'), ('private', '非公開')], default='private', max_length=20, verbose_name='公開or非公開'),
        ),
    ]
