# Generated by Django 3.1.1 on 2020-11-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esuits', '0018_auto_20201129_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyhomepageurlmodel',
            name='word_cloud_path',
            field=models.CharField(blank=True, default='dummy_path', max_length=255, verbose_name='ワードクラウドパス'),
        ),
    ]
